apiVersion: v1
kind: ServiceAccount
metadata:
  name: iris-service-python
  namespace: iris
  labels:
    app.kubernetes.io/name: iris-service-python
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: iris
automountServiceAccountToken: false  # the deployment doesn't talk to k8s API
