#!/usr/bin/env python3
"""Wrap Sloth's raw rules as a kube-prometheus-stack PrometheusRule CRD.

Mirror of iris-service-java/docs/slo/wrap-as-prometheusrule.py for the
Python side. Output goes to iris-py-slo.yaml in the shared submodule
to keep all SLO PrometheusRules together for the operator's ruleSelector.

Usage :
  cd <repo>/iris-service-python
  sloth generate -i docs/slo/slo.yaml -o /tmp/iris-py-slo-rules.yaml
  python3 docs/slo/wrap-as-prometheusrule.py
"""

from __future__ import annotations

import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parents[2]
SHARED_DIR = REPO_ROOT
INPUT = Path("/tmp/iris-py-slo-rules.yaml")  # noqa: S108 — dev-only generator script, never runs in prod
OUTPUT = REPO_ROOT / "deploy/kubernetes/observability-prom/iris-py-slo.yaml"

HEADER = """# =============================================================================
# deploy/kubernetes/observability-prom/iris-py-slo.yaml
#
# Python service SLO recording + multi-window multi-burn-rate alerting rules.
# Generated by Sloth from `iris-service-python/docs/slo/slo.yaml`,
# wrapped as PrometheusRule CRD by `wrap-as-prometheusrule.py`.
#
# Same pattern as the Java side's iris-slo.yaml ; both are picked up by
# the kube-prometheus-stack operator via the `release: prometheus-stack`
# ruleSelector label.
# =============================================================================
"""


def main() -> int:
    if not INPUT.exists():
        print(f"ERROR: {INPUT} not found. Run `sloth generate` first.", file=sys.stderr)
        return 1

    with INPUT.open() as f:
        sloth = yaml.safe_load(f)

    prom_rule = {
        "apiVersion": "monitoring.coreos.com/v1",
        "kind": "PrometheusRule",
        "metadata": {
            "name": "iris-py-slo",
            "labels": {
                "release": "prometheus-stack",
                "role": "alert-rules",
                "app.kubernetes.io/part-of": "iris",
                "app.kubernetes.io/component": "python-service",
            },
        },
        "spec": {
            "groups": sloth["groups"],
        },
    }

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    with OUTPUT.open("w") as f:
        f.write(HEADER)
        yaml.safe_dump(prom_rule, f, default_flow_style=False, sort_keys=False, width=120)

    total_records = sum(len([r for r in g["rules"] if "record" in r]) for g in sloth["groups"])
    total_alerts = sum(len([r for r in g["rules"] if "alert" in r]) for g in sloth["groups"])
    print(f"Wrote {OUTPUT}")
    print(f"  groups: {len(sloth['groups'])} | recording: {total_records} | alerts: {total_alerts}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
